[build]
builder = "dockerfile"
dockerfilePath = "web/services/pose-extract-server/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[mounts]]
source = "data"
destination = "/app/data"
